/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type CartStatus = "abandoned" | "active" | "converted";

export type CouponKind = "flat" | "percent";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type OrderStatus = "assigned" | "cancelled" | "delivered" | "failed" | "out_for_delivery" | "packed" | "paid" | "pending_payment" | "reserved";

export type PaymentStatus = "failed" | "pending" | "refunded" | "succeeded";

export type ReservationStatus = "committed" | "expired" | "held" | "released";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "customer" | "picker" | "rider";

export interface Addresses {
  city: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_default: Generated<boolean>;
  label: string | null;
  lat: number;
  line1: string;
  line2: string | null;
  lng: number;
  pincode: string;
  state: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Brands {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  name: string;
  slug: string;
}

export interface CartItems {
  cart_id: string;
  created_at: Generated<Timestamp>;
  product_id: string;
  quantity: number;
  updated_at: Generated<Timestamp>;
}

export interface Carts {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  status: Generated<CartStatus>;
  store_id: string;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface Categories {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  name: string;
  parent_id: string | null;
  slug: string;
  sort_order: Generated<number>;
}

export interface Coupons {
  code: string;
  created_at: Generated<Timestamp>;
  is_active: Generated<boolean>;
  kind: CouponKind;
  max_discount_paise: number | null;
  min_order_paise: Generated<number>;
  per_user_limit: Generated<number>;
  usage_limit: number | null;
  used_count: Generated<number>;
  valid_from: Generated<Timestamp>;
  valid_until: Timestamp | null;
  value: number;
}

export interface Inventory {
  product_id: string;
  quantity: Generated<number>;
  reserved: Generated<number>;
  store_id: string;
  updated_at: Generated<Timestamp>;
}

export interface InventoryLedger {
  created_at: Generated<Timestamp>;
  delta_qty: number;
  delta_res: number;
  id: Generated<Int8>;
  product_id: string;
  reason: string;
  reference: string | null;
  store_id: string;
}

export interface OrderItems {
  id: Generated<string>;
  line_total_paise: Int8;
  order_id: string;
  product_id: string;
  product_name: string;
  product_unit: string;
  quantity: number;
  unit_price_paise: number;
}

export interface Orders {
  address_id: string | null;
  cancellation_reason: string | null;
  cancelled_at: Timestamp | null;
  coupon_code: string | null;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  delivery_address: Json;
  delivery_fee_paise: Generated<Int8>;
  discount_paise: Generated<Int8>;
  id: Generated<string>;
  order_number: string;
  placed_at: Generated<Timestamp>;
  status: Generated<OrderStatus>;
  store_id: string;
  subtotal_paise: Int8;
  total_paise: Int8;
  updated_at: Generated<Timestamp>;
  user_id: string;
}

export interface OrderStatusHistory {
  actor: string | null;
  created_at: Generated<Timestamp>;
  from_status: OrderStatus | null;
  id: Generated<Int8>;
  order_id: string;
  reason: string | null;
  to_status: OrderStatus;
}

export interface Payments {
  amount_paise: Int8;
  attempt: Generated<number>;
  created_at: Generated<Timestamp>;
  failure_code: string | null;
  id: Generated<string>;
  order_id: string;
  provider: Generated<string>;
  provider_ref: string | null;
  status: Generated<PaymentStatus>;
  updated_at: Generated<Timestamp>;
}

export interface Products {
  brand_id: string | null;
  category_id: string | null;
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  image_url: string | null;
  is_active: Generated<boolean>;
  name: string;
  sku: string;
  slug: string;
  unit_label: string;
  updated_at: Generated<Timestamp>;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  family_id: string;
  id: Generated<string>;
  ip: string | null;
  replaced_by: string | null;
  revoked_at: Timestamp | null;
  token_hash: string;
  user_agent: string | null;
  user_id: string;
}

export interface Reservations {
  created_at: Generated<Timestamp>;
  expires_at: Timestamp;
  id: Generated<string>;
  order_id: string | null;
  product_id: string;
  quantity: number;
  status: Generated<ReservationStatus>;
  store_id: string;
  updated_at: Generated<Timestamp>;
}

export interface StoreProducts {
  created_at: Generated<Timestamp>;
  is_listed: Generated<boolean>;
  mrp_paise: number;
  price_paise: number;
  product_id: string;
  store_id: string;
  updated_at: Generated<Timestamp>;
}

export interface Stores {
  closes_at: Generated<string>;
  code: string;
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  is_active: Generated<boolean>;
  lat: number;
  lng: number;
  name: string;
  opens_at: Generated<string>;
  service_radius_m: Generated<number>;
  updated_at: Generated<Timestamp>;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  email_verified_at: Timestamp | null;
  id: Generated<string>;
  password_hash: string;
  phone: string | null;
  role: Generated<UserRole>;
  updated_at: Generated<Timestamp>;
}

export interface DB {
  addresses: Addresses;
  brands: Brands;
  cart_items: CartItems;
  carts: Carts;
  categories: Categories;
  coupons: Coupons;
  inventory: Inventory;
  inventory_ledger: InventoryLedger;
  order_items: OrderItems;
  order_status_history: OrderStatusHistory;
  orders: Orders;
  payments: Payments;
  products: Products;
  refresh_tokens: RefreshTokens;
  reservations: Reservations;
  store_products: StoreProducts;
  stores: Stores;
  users: Users;
}
